config/routes.rb
Rails.application.routes.draw do
  
  resources :colleges
  resources :members
  resources :profiles
  get 'static_pages/index'
  get 'static_pages/home'
  get 'static_pages/members'
  resources :conversations do
    resources :messages
  end
  resources :channels 
  resources :subjects 
  resources :friendships
  resources :friends 
  resources :forums do 
  resources :replies

end 

 

  root 'static_pages#home'
  get '/members' => 'static_pages#members'

  get '/myposts' => 'static_pages#myposts'

  get '/friends' => 'friends#myFriends'
  get '/home' => 'static_pages#home'
  get '/browseforums' => 'subjects#browseforums'
  #get '/profile' => 'static_pages#profile'
  get '/profiles/:user_id' => 'profiles#index'

  get '/replies/like/:id' => 'replies#like'
  get '/replies/dislike/:id' => 'replies#dislike' 
  get '/profiles/like/:id' => 'profiles#like'
  get '/profiles/dislike/:id' => 'profiles#dislike' 

  #get '/search' => 'static_pages#search' 
  post '/search' => 'forums#search'
  
  get '/search' => 'static_pages#searchforums'

  get '/upgrade/:id' => 'static_pages#upgrade'
  get '/downgrade/:id' => 'static_pages#downgrade'


  devise_for :users, controllers: {registrations: 'registrations', confirmations: 'confirmations'}
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  #before_action :set_member, only: [:show, :edit, :update, :destroy, :create]
 

  STATUS_PER_PAGE = 5
  

  # GET /profiles
  # GET /profiles.json
  def index
    
   
   @user = User.all.where('id = ?',current_user.id)
   @recentforum = Forum.all.where('user_id = ?', current_user.id).order('created_at DESC')
   @profile = Profile.new

   #pagination
   @totalstatus = Profile.count
   @limitPages = @totalstatus / STATUS_PER_PAGE
   @page = params.fetch(:page,0).to_i
   @profiles = Profile.all.where('user_id = ?', current_user.id).order('created_at DESC').offset(@page * STATUS_PER_PAGE).limit(STATUS_PER_PAGE)
     
    
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
   #@user = current_user
   @user = User.find(params[:id])
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
    @findstatus = Profile.find(params[:id])
    
  end


  # POST /profiles
  # POST /profiles.json
  def create

    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id
    #@profile.isowner = @user.id


    respond_to do |format|
      if @profile.save
        format.html { redirect_to request.referrer, notice: 'Successfully created status.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    @profile = Profile.find(params[:id])
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to profiles_path, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def dislike

    @profile = Profile.find_by(id: params[:id])
    @profile.update_attribute(:dislikes, @profile.dislikes+1)
    redirect_to profile_path(@profile.id)
     
  end
  
  def like
    
    @profile = Profile.find_by(id: params[:id])
    @profile.update_attribute(:likes, @profile.likes+1)
     redirect_to profile_path(@profile.id) 
    
         
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def set_member
      @member= User.find(params[:id])
    end



    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:status, :about, :user_id, :isowner)
    end

    
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
<h3 class="title is-5 has-text-black-light">Status</h3>
   <div class="field has-addons">
   
     <%= f.input :status, input_html: { class: 'input' }, wrapper: false,  label_html:{ class: 'label' },label: false%>
      <%= f.button :submit, 'Post Status', class: 'button is-info' %>
  
 </div>

 


<% end %>

app/views/profiles/_profileleft.html.erb
   <% @user.each do |user| %>
   <h3 class="title is-5 has-text-black-light"><%= user.username %></h3>
   <%= gravatar_image_tag(user.email, class:'border-radius-50', size: 48, alt: user.username) %>
   <hr />
  
 
      <% if user.username != current_user.username %> 
        <%= link_to "Add Friend", friendships_path(:friend_id => user), :method => :post, class:"button is-info" %>
      <% end %>
     
<%= link_to "My Friends", { :controller => "friends", :action => "show", :id => current_user } %>
  
  <h3 class="title is-5 has-text-black-light">Info</h3>
    	<p><strong>First name:</strong> <%= user.firstname %></p>
    	<p><strong>Last name:</strong> <%= user.lastname %></p>
    	<p><strong>College:</strong> <%= user.college %></p>
      <p><strong>Studying:</strong> <%= user.studying %></p>
    	<p><strong>Joined:</strong> <%= time_ago_in_words(user.created_at) %> ago </p>
      
  <% end %>
<hr />

  <h3 class="title is-5 has-text-black-light">Recent forum posts</h3>
  <% @recentforum.each do |forum| %>
   <%= link_to forum do %>
    <p><strong><%= forum.title %></strong> <%= time_ago_in_words(forum.created_at) %> ago </p>
    <% end %>
    <% end %>
  <br/>

  

app/views/profiles/_profileright.html.erb
<% if user_signed_in? && current_user.id != @user.id %>
      <%= link_to "Message #{@user.username}", conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: 'post', class:"button is-info" %>
    <% end %>
</br></br>
   <h3 class="title is-5 has-text-black-light"><strong>About <%= @user.username %></strong></h3>
   <p><%= @user.about %></p>
  
     

app/views/profiles/_status.html.erb
<%= simple_form_for(@profile) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  
     <div class="field">
	<div class="control">
    <%= f.input :status %>
  </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>
<div class="columns">
  <div class="column is-one-quarter">
    <%= render 'profileleft' %>
  </div>
  <div class="column is-two-quarter">
    <%= render 'form', profile: @profile %>
    <br />
<%= render 'shared/profiles' %>
 
  </div>
  <div class="column is-one-quarter">
    <%= render 'profileright' %>
  </div>
 
</div>
 


<br>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @profile.status %>
</p>

<p>
  <strong>About:</strong>
  <%= @profile.about %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>