config/routes.rb
Rails.application.routes.draw do
  
  resources :colleges
  resources :members
  resources :profiles
  get 'static_pages/index'
  get 'static_pages/home'
  get 'static_pages/members'
  resources :conversations do
    resources :messages
  end
  resources :channels 
  resources :subjects 
  resources :friendships
  resources :friends 
  resources :forums do 
  resources :replies

end 

 

  root 'static_pages#home'
  get '/members' => 'static_pages#members'

  get '/myposts' => 'static_pages#myposts'

  get '/friends' => 'friends#myFriends'
  get '/home' => 'static_pages#home'
  get '/browseforums' => 'subjects#browseforums'
  #get '/profile' => 'static_pages#profile'
  get '/profiles/:user_id' => 'profiles#index'

  get '/replies/like/:id' => 'replies#like'
  get '/replies/dislike/:id' => 'replies#dislike' 
  get '/profiles/like/:id' => 'profiles#like'
  get '/profiles/dislike/:id' => 'profiles#dislike' 

  #get '/search' => 'static_pages#search' 
  post '/search' => 'forums#search'
  
  get '/search' => 'static_pages#searchforums'

  get '/upgrade/:id' => 'static_pages#upgrade'
  get '/downgrade/:id' => 'static_pages#downgrade'


  devise_for :users, controllers: {registrations: 'registrations', confirmations: 'confirmations'}
end

app/models/forum.rb
class Forum < ApplicationRecord

  belongs_to :subject
  belongs_to :user
  has_many :replies, dependent: :destroy # if forum is destroyed so are the replies

  validates :title, :content, presence: true # validates that their is content to reply
  resourcify

end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_action :set_forum, only: [:show, :edit, :update, :destroy]
  before_action :find_subjects, only: [:index, :show, :new, :edit]
  before_action :authenticate_user!, except: [:index, :show]

  FORUMS_PER_PAGE = 5
  #SEARCH_PER_PAGE = 5

  # GET /forums
  # GET /forums.json
  def index
    @forums = Forum.all.order('created_at desc')
    @subjects = Subject.all.order('created_at desc')

    # pagination for all posts
    @totalforums = Forum.count
    @limitPages = @totalforums / FORUMS_PER_PAGE
    @page = params.fetch(:page,0).to_i
    @forums = Forum.all.order('created_at desc').offset(@page * FORUMS_PER_PAGE).limit(FORUMS_PER_PAGE)
    @forumscount = Forum.all
  
   
  end

  # GET /forums/1
  # GET /forums/1.json
  def show
     @forums = Forum.all.order('created_at desc')
    @subjects = Subject.all.order('created_at desc')
   
  end

  # GET /forums/new
  def new
    @forum = current_user.forums.build
  end

  # GET /forums/1/edit
  def edit
  end

  def search
    
     st = "%#{params[:q]}%"
     @forums = Forum.where("title like ?", st).or(Forum.where("content like ?", st))
    

    # pagination for search
    @totalsearch = @forums.count
    #@limitPages = @totalsearch / SEARCH_PER_PAGE
    #@page = params.fetch(:page,0).to_i
    #@forums = Forum.where("title like ?", st).or(Forum.where("content like ?", st)).offset(@page * SEARCH_PER_PAGE).limit(SEARCH_PER_PAGE)
    @forumscount = @totalsearch
  end

  # POST /forums
  # POST /forums.json
  def create
    @forum = current_user.forums.build(forum_params)

    respond_to do |format|
      if @forum.save
        format.html { redirect_to @forum, notice: 'Forum was successfully created.' }
        format.json { render :show, status: :created, location: @forum }
      else
        format.html { render :new }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forums/1
  # PATCH/PUT /forums/1.json
  def update
    respond_to do |format|
      if @forum.update(forum_params)
        format.html { redirect_to @forum, notice: 'Forum was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum }
      else
        format.html { render :edit }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1
  # DELETE /forums/1.json
  def destroy
    @forum.destroy
    respond_to do |format|
      format.html { redirect_to forums_url, notice: 'Forum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum
      @forum = Forum.find(params[:id])
    end

    def find_subjects
      @subjects = Subject.all.order('created_at desc')
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_params
      params.require(:forum).permit(:title, :content, :subject_id)
    end
end

app/helpers/forums_helper.rb
module ForumsHelper

	def forum_is_owner(forum)
    user_signed_in? && current_user.id == forum.user_id
  end

  def reply_is_owner(reply)
    user_signed_in? && current_user.id == reply.user_id
  end

end

app/views/forums/_form.html.erb
<%= simple_form_for(@forum) do |f| %>
  <%= f.error_notification %>

  <div class="field">
    <div class="control">
      <%= f.input :title, required: true, input_html: { class: 'input' }, wrapper: false, label_html: { class: "label" } %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.input :content, required: true, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: "label" } %>
    </div>
  </div>

  <div class="field">
    <label class="label">Select which section to post to</label>
    <div class="control has-icons-left">
      <span class="select">
        <%= f.input_field :subject_id, collection:@subjects.map { |s| [s.subject, s.id] }, prompt: "Select section" %>
      </span>
      <span class="icon is-small is-left">
        <i class="fa fa-tag"></i>
      </span>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.button :submit, class:"button is-info" %>
    </div>
  </div>

<% end %>

app/views/forums/edit.html.erb
<h1 class="title is-3">Editing Forum</h1>

<%= render 'form', forum: @forum %>

<%= link_to 'Show', @forum %> |
<%= link_to 'Back', forums_path %>

app/views/forums/index.html.erb
<div class="columns">
  <%= render 'shared/forums' %>
  
</div>

app/views/forums/new.html.erb
<h1 class="title is-size-3">Create a new Forum Post</h1>

<%= render 'form', forum: @forum %>

<%= link_to 'Back', forums_path %>

app/views/forums/search.html.erb
<div class="columns is-mobile is-centered">
  <div class="column is-three-quarters">
    <% if @forums.length == 0  %>

<h2>No results were found to match your search</h2>
<% end %>
</div>
</div>

 


<div class="column">
  <h3 class="title is-5 has-text-black-light">Search results <%= @forumscount %></h3>
  <div class="forums">
    <% @forums.each do |forum| %>
      <div class="columns bb-not-last pv10">
        <div class="column is-1">
          <%= gravatar_image_tag(forum.user.email, class:'border-radius-50', size: 48, alt: forum.user.username) %>
        </div>
        <div class="column ">
          <%= link_to forum do %>
            <h3 class="title is-5"><%= forum.title %></h3>
          <% end %>
          <div class="content">
            <%= truncate(forum.content, length: 140) %>
            <p><em><small>Posted <%= time_ago_in_words(forum.created_at) %> ago in
              <% if forum.subject %>
                <%= link_to forum.subject.subject, forum.subject %>
              <% end %>
              by <%= forum.user.username %>
              </small>
              </em>
            </p>
          </div>
        </div>

   

      </div>
    <% end %>
  </div>
</div>

app/views/forums/show.html.erb
<div class="column is-full">
  <div class="forums"> 
 <article class="media">
  <figure class="media-left">
    <p class="image is-64x64">
      <%= gravatar_image_tag(@forum.user.email, class:'border-radius-50', size: 48, alt: @forum.user.username) %>
    </p>
  </figure>
   <div class="column is-8">
            <h1 class="title is-8"><%= @forum.title %></h1>
  <div class="media-content">
    <div class="content">
      <p>
        <strong><%= @forum.user.username %></strong> <small>Posted <%= time_ago_in_words(@forum.created_at) %> ago</small> in
              <% if @forum.subject %>
                <%= link_to @forum.subject.subject, @forum.subject %>
              <% end %> section
        <br>
         <%= @forum.content %>
      </p>
    </div>
    <nav class="level is-mobile">
      <div class="level-left">
        <a class="level-item">
          <span class="icon is-small"><i class="fa fa-reply"></i></span>
        </a>
        <p class="level-item">
          <%= @forum.replies.count %> Replies
        </p>
      </div>
    </nav>
    <div id="forum-replies">
      <%= render @forum.replies.order(likes: :desc) %>
    </div>
    <hr />
    <h3 class="subtitle is-3 has-text-grey">Leave a reply</h3>
    <% if user_signed_in? %>
      <%= render 'replies/form' %>
    <% else %>
    <p>To reply you need to <%= link_to 'login', new_user_session_path %>. Don't have an account?
      <%= link_to 'Sign up', new_user_registration_path %> for one.</p>
    <% end %>
  </div>
  </div>
  <div class="media-right">
    <% if user_signed_in? %>
        <% if forum_is_owner(@forum) || current_user.admin? %> 
        <div class="column has-text-right">
          <%= link_to 'Edit', edit_forum_path(@forum), class:'button' %>
          <%= link_to 'Delete', forum_path(@forum), method: :delete, data: { confirm: "Delete forum?" }, class:'button' %>

        </div>
        <% end %>
        <% end %>
  </div>
</article>
</div>
</div>