config/routes.rb
Rails.application.routes.draw do
  
  resources :colleges
  resources :members
  resources :profiles
  get 'static_pages/index'
  get 'static_pages/home'
  get 'static_pages/members'
  resources :conversations do
    resources :messages
  end
  resources :channels 
  resources :subjects 
  resources :friendships
  resources :friends 
  resources :forums do 
  resources :replies

end 

 

  root 'static_pages#home'
  get '/members' => 'static_pages#members'

  get '/myposts' => 'static_pages#myposts'

  get '/friends' => 'friends#myFriends'
  get '/home' => 'static_pages#home'
  get '/browseforums' => 'subjects#browseforums'
  #get '/profile' => 'static_pages#profile'
  get '/profiles/:user_id' => 'profiles#index'

  get '/replies/like/:id' => 'replies#like'
  get '/replies/dislike/:id' => 'replies#dislike' 
  get '/profiles/like/:id' => 'profiles#like'
  get '/profiles/dislike/:id' => 'profiles#dislike' 

  #get '/search' => 'static_pages#search' 
  post '/search' => 'forums#search'
  
  get '/search' => 'static_pages#searchforums'

  get '/upgrade/:id' => 'static_pages#upgrade'
  get '/downgrade/:id' => 'static_pages#downgrade'


  devise_for :users, controllers: {registrations: 'registrations', confirmations: 'confirmations'}
end

app/views/shared/_forums.html.erb
 <div class="column is-full">
  <h3 class="title is-5 has-text-black"><%= @forumscount.count %> forum posts</h3>
 </br></br>
  <div class="forums"> 
    <% if @forumscount.count == 0 %>
      <div class="content">
        <h3> Be the first to post in this section...</h3>
      </br>
        <%= link_to 'Create New Post', new_forum_path, class:"button is-info" %>
      </div>
      <% else %>
      <% @forums.each do |forum| %>
 <article class="media">
  <figure class="media-left">
    <p class="image is-64x64">
      <%= gravatar_image_tag(forum.user.email, class:'border-radius-50', size: 48, alt: forum.user.username) %>
    </p>
  </figure>
   <div class="column is-8">
          <%= link_to forum do %>
            <h1 class="title is-8"><%= forum.title %></h1>
          <% end %>
  <div class="media-content">
    <div class="content">
      <p>
        <strong><%= forum.user.username %></strong> <small>Posted <%= time_ago_in_words(forum.created_at) %> ago</small> in
              <% if forum.subject %>
                <%= link_to forum.subject.subject, forum.subject %>
              <% end %> section
        <br>
         <%= truncate(forum.content, length: 140) %>
      </p>
    </div>
    <nav class="level is-mobile">
      <div class="level-left">
        <a class="level-item">
          <span class="icon is-small"><i class="fa fa-reply"></i></span>
        </a>
        <p class="level-item">
          <%= forum.replies.count %> Replies
        </p>
      </div>
    </nav>
  </div>
  <div class="media-right">
    <% if user_signed_in? %>
        <% if forum_is_owner(forum) || current_user.admin? %> 
        <div class="column has-text-right">
          <%= link_to 'Edit', edit_forum_path(forum), class:'button' %>
          <%= link_to 'Delete', forum, method: :delete, data: { confirm: 'Are you sure?' }, class: "button" %>

        </div>
        <% end %>
        <% end %>
  </div>
</article>
<% end %>
<% end %>

      <% if @page > 0%>
      <%= link_to "Previous", forums_path(page: @page - 1), class:"pagination-previous" %>     
      <% end %>

      <% if @page < @limitPages%>
      <%= link_to "Next Page", forums_path(page: @page + 1), class:"pagination-next" %> 
      <% end %>   

app/views/shared/_members.html.erb
<div class="container">
  <div class="column is-10">
  <div class="forums">
    <% @users.each do |user| %>
      <div class="columns bb-not-last pv10">
        <div class="column is-1">
          <a href="/members/<%= user.id %>">
          <%= gravatar_image_tag(user.email, class:'border-radius-50', size: 48, alt: user.username) %>
        </a>
        </div>
        <div class="column is-10">
          
            <h3><strong><%= user.username%></strong> Joined: <%= time_ago_in_words(user.created_at) %> Id: <%= user.id %>
            
      <% if user.username != current_user.username %>
        
        <%= link_to "Add Friend", friendships_path(:friend_id => user), :method => :post %>
      <% end %></h3>
            <h5><strong>College:</strong> <%= user.college%> <strong>Studying:</strong> <%= user.studying%></h5>
          <br/>
          <div class="content">
            <%= truncate (user.about), length: 200 %>
           
          </div>
        </div>

        

      </div>
    <% end %>
    <div>
      <% if @page < @limitPages%>
      <%= link_to "Next Page", members_path(page: @page + 1) %> 
        <% end %>
        |
      <% if @page > 0%>
      <%= link_to "Last Page", members_path(page: @page - 1) %>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/shared/_profiles.html.erb
<div class="forums">
    <% @profiles.each do |profile| %>
      <div class="box">
        <article class="media">
          <div class="media-left">
           <figure class="image is-48x48">
             <%= gravatar_image_tag(profile.user.email, class:'border-radius-50', size: 48, alt: profile.user.username) %>
          </figure>
         </div>
       <div class="media-content">
        <div class="content">
            <%= truncate(profile.status, length: 140) %> 
            <p><em><small>Posted <%= time_ago_in_words(profile.created_at ) %> ago in </small></em> </p>
        </div>
      </div>

      <nav class="level is-mobile">
        <div class="level-left">
          <a class="level-item">
            <%= link_to edit_profile_path(profile) do %>
            <span class="icon is-small"><i class="fa fa-pencil"></i></span>
            <% end %>
          </a>

          <a class="level-item">
            <%= link_to [profile], method: :delete, data: {confirm: "Are you sure ?" } do %>
            <span class="icon is-small"><i class="fa fa-trash-o"></i></span>
            <% end %>
          </a>
          
        </div>
      </nav> 
    </article>
  </div>
  <% end %>
</div>

  <% if @page > 0%>
    <%= link_to "Last Page", member_path(page: @page - 1), class:"pagination-previous" %>
  <% end %>

  <% if @page < @limitPages%>   
    <%= link_to "Next Page", member_path(page: @page + 1), class:"pagination-next" %> 
  <% end %>

app/views/shared/_subjects.html.erb
<div class="column is-8">
  <h3 class="title is-5 has-text-grey-light">Latest forum posts</h3>
  <div class="forums">
    <% @forums.each do |forum| %>
      <div class="columns bb-not-last pv10">
        <div class="column is-1">
          <%= gravatar_image_tag(forum.user.email, class:'border-radius-50', size: 48, alt: forum.user.username) %>
        </div>
        <div class="column is-8">
          <%= link_to forum do %>
            <h3 class="title is-5"><%= forum.title %></h3>
          <% end %>
          <div class="content">
            <%#= truncate(strip_markdown(forum.content), length: 140) %>
            <p><em><small>Posted <%= time_ago_in_words(forum.created_at) %> ago in
              <% if forum.subject %>
                <%= link_to forum.subject.subject, forum.subject %>
              <% end %>
              by <%= forum.user.username %>
              </small>
              </em>
            </p>
          </div>
        </div>

        <%# if forum_author(forum) || has_role?(:admin) %>
        <div class="column has-text-right">
          <%= link_to 'Edit', edit_forum_path(forum), class:'button' %>
          <%= link_to 'Delete', forum, method: :delete, data: { confirm: 'Are you sure?' }, class: "button" %>
        </div>
        <%# end %>

      </div>
    <% end %>
  </div>
</div>