config/routes.rb
Rails.application.routes.draw do
  
  resources :colleges
  resources :members
  resources :profiles
  get 'static_pages/index'
  get 'static_pages/home'
  get 'static_pages/members'
  resources :conversations do
    resources :messages
  end
  resources :channels 
  resources :subjects 
  resources :friendships
  resources :friends 
  resources :forums do 
  resources :replies

end 

 

  root 'static_pages#home'
  get '/members' => 'static_pages#members'

  get '/myposts' => 'static_pages#myposts'

  get '/friends' => 'friends#myFriends'
  get '/home' => 'static_pages#home'
  get '/browseforums' => 'subjects#browseforums'
  #get '/profile' => 'static_pages#profile'
  get '/profiles/:user_id' => 'profiles#index'

  get '/replies/like/:id' => 'replies#like'
  get '/replies/dislike/:id' => 'replies#dislike' 
  get '/profiles/like/:id' => 'profiles#like'
  get '/profiles/dislike/:id' => 'profiles#dislike' 

  #get '/search' => 'static_pages#search' 
  post '/search' => 'forums#search'
  
  get '/search' => 'static_pages#searchforums'

  get '/upgrade/:id' => 'static_pages#upgrade'
  get '/downgrade/:id' => 'static_pages#downgrade'


  devise_for :users, controllers: {registrations: 'registrations', confirmations: 'confirmations'}
end

app/models/subject.rb
class Subject < ApplicationRecord
 
  has_many :forums
  has_many :users, through: :forums # has many users throught the forums
  resourcify


end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :browseforums]

   FORUMS_PER_PAGE = 5

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
    @forums = Forum.all.order('created_at desc')

    
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
    @forums = Forum.where('subject_id = ?', @subject.id)
    @subjects = Subject.all
    
    @totalforums = @forums.count
    @limitPages = @totalforums / FORUMS_PER_PAGE
    @page = params.fetch(:page,0).to_i
    @forums = @forums.offset(@page * FORUMS_PER_PAGE).limit(FORUMS_PER_PAGE)
    @forumscount = @forums.all
    
  end

  def browseforums
     @subject = Subject.all
     @subjects = Subject.all
     @forums = Forum.all
     #current_user.update_attribute :admin, true
     #@forumscount = @forums.where('subject_id = ?', @subject.id).count
  
    
    
    
     
  
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to subjects_path, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to subject_path, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:subject, :forum_id, :channel_id)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= simple_form_for(@subject) do |f| %>
  <%= f.error_notification %>

 <div class="field">
   <div class="control">
     <%= f.input :subject, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
   </div>
 </div>

  

 <%= f.button :submit, class: 'button is-info' %>
<% end %>

app/views/subjects/browseforums.html.erb
<h3 class="title is-2 has-text-grey forum-title">Browse Alumni Ireland forums</h3></br></br>
<div class="columns is-multiline">
  <% @subjects.each do |s| %>
  <div class="column is-one-third">
  <div class="box is-one-third">
   <p class="control"><%= link_to s.subject, s %></p>
   	
   </div>
 </div></br></br></br>
 
  <% end %>
</div>

 

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<h1 class="title is-2">Subjects</h1>

 <% if user_signed_in? && current_user.admin? %>
<div class="level">
  <div class="level-left"></div>
  <div class="level-right">
    <%= link_to 'New Subject', new_subject_path, class:'button is-dark' %>
  </div>
</div>

<table class="table is-fullwidth">
  <thead>
    <tr>
      <th>Subject</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @subjects.each do |subject| %>
    <tr>
      <td><%= link_to subject.subject, subject %>  <%= @forumscount %></td>
      <td>
        <div class="buttons is-right">
          
          <%= link_to 'View Subject', subject, class:'button' %>
          <%= link_to 'Edit Subject', edit_subject_path(subject), class:'button' %>
          <%= link_to 'Delete', subject, class:'button is-danger', method: :delete, data: { confirm: "Are you sure you want to delete this subject? " } %>
        
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>

</table>

<% else %>
 <p class="has-text-center">Sorry! You don't have access this page.</p>
</br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br>
<% end %>

app/views/subjects/new.html.erb
<div class="columns is-centered">
  <div class="column is-4">
    <h1 class="title is-3">Create a new subject</h1>
    <%= render 'form', subject: @subject %>
    </br></br></br></br></br>
    </br></br></br></br></br>
  
  </div>

</div>

app/views/subjects/show.html.erb
<div class="level">
  <div class="level-left">
  <h1 class="title is-2"><%= @subject.subject %></h1>
  </div>
</div>
<hr />

<div class="columns">
 <%= render 'shared/forums' %>
</div>
</br></br></br></br></br></br>
</br></br></br></br></br></br>